# Generated by Django 6.0 on 2026-01-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Dipinjam', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.barang')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.peminjam')),
            ],
        ),
    ]
