# Generated by Django 6.0 on 2026-01-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='peminjam',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_kembali',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='jumlah',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='nama_peminjam',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='Dipinjam', max_length=20),
        ),
    ]
