# Generated by Django 6.0 on 2026-01-03 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0002_remove_peminjaman_peminjam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyimpanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal_simpan', models.DateField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.barang')),
            ],
        ),
    ]
