# Generated by Django 6.0 on 2026-01-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0003_penyimpanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True),
        ),
    ]
